### ISSUE TITLE
Write `Roadmap` page in docs

### ISSUE THREAD

**Issue by adamkelso** [blastcloud/guzzler#4]
Include:

- [x] Make outline to fill out

- [x] Idea for `Drive`
    - [x] For working with OpenAPI and others docs
    - [x] Response factories modeled after Laravel model factories
    - [x] `validate()` method on expectations.
    - [x] Possible syntaxes
- [x] Idea for `MPG`
    - [x] Show PHPUnit coverage report as example
    - [x] Show possible idea for report
    - [x] Mention new coverage standard that would be needed.

**Comment by adamkelso** [comment]
Published June 6, 2019.
